# Generated by Django 4.2.26 on 2026-01-16 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_platform', '0049_add_ranking_metrics_to_quicktest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name in Vertex AI Model Registry', max_length=255)),
                ('run_number', models.IntegerField(help_text='Auto-increment run number per model endpoint')),
                ('description', models.TextField(blank=True, help_text='User-provided description of this training run')),
                ('model_type', models.CharField(choices=[('retrieval', 'Retrieval'), ('ranking', 'Ranking'), ('multitask', 'Multitask')], default='retrieval', help_text='Type of model being trained', max_length=20)),
                ('training_params', models.JSONField(default=dict, help_text='Training hyperparameters (epochs, batch_size, learning_rate, etc.)')),
                ('gpu_config', models.JSONField(default=dict, help_text='GPU configuration (machine_type, accelerator_type, accelerator_count)')),
                ('evaluator_config', models.JSONField(default=dict, help_text='Model evaluation configuration (blessing thresholds, metrics)')),
                ('deployment_config', models.JSONField(default=dict, help_text='Deployment configuration (auto_deploy, endpoint settings)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('submitting', 'Submitting'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('not_blessed', 'Not Blessed')], db_index=True, default='pending', help_text='Current status of the training run', max_length=20)),
                ('current_stage', models.CharField(blank=True, help_text="Current pipeline stage (e.g., 'ExampleGen', 'Trainer')", max_length=100)),
                ('current_epoch', models.IntegerField(blank=True, help_text='Current training epoch (for progress tracking)', null=True)),
                ('total_epochs', models.IntegerField(blank=True, help_text='Total number of training epochs', null=True)),
                ('progress_percent', models.IntegerField(default=0, help_text='Overall progress percentage (0-100)')),
                ('stage_details', models.JSONField(default=list, help_text='Detailed status of each pipeline stage')),
                ('cloud_build_id', models.CharField(blank=True, help_text='Cloud Build job ID for pipeline compilation', max_length=255)),
                ('cloud_build_run_id', models.CharField(blank=True, help_text='Cloud Build run ID', max_length=255)),
                ('vertex_pipeline_job_name', models.CharField(blank=True, help_text='Vertex AI Pipeline job name', max_length=500)),
                ('gcs_artifacts_path', models.CharField(blank=True, help_text='GCS path for training artifacts', max_length=500)),
                ('loss', models.FloatField(blank=True, help_text='Final training loss', null=True)),
                ('recall_at_5', models.FloatField(blank=True, help_text='Recall@5 metric for retrieval models', null=True)),
                ('recall_at_10', models.FloatField(blank=True, help_text='Recall@10 metric for retrieval models', null=True)),
                ('recall_at_50', models.FloatField(blank=True, help_text='Recall@50 metric for retrieval models', null=True)),
                ('recall_at_100', models.FloatField(blank=True, help_text='Recall@100 metric for retrieval models', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Square Error (validation set)', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error (validation set)', null=True)),
                ('test_rmse', models.FloatField(blank=True, help_text='Root Mean Square Error (test set)', null=True)),
                ('test_mae', models.FloatField(blank=True, help_text='Mean Absolute Error (test set)', null=True)),
                ('is_blessed', models.BooleanField(help_text='Whether the model passed evaluation (blessing)', null=True)),
                ('evaluation_results', models.JSONField(default=dict, help_text='Detailed evaluation results from model evaluation')),
                ('vertex_model_name', models.CharField(blank=True, help_text='Vertex AI Model Registry model name', max_length=500)),
                ('vertex_model_version', models.CharField(blank=True, help_text='Vertex AI Model Registry version', max_length=100)),
                ('vertex_model_resource_name', models.CharField(blank=True, help_text='Full Vertex AI Model resource name', max_length=500)),
                ('is_deployed', models.BooleanField(default=False, help_text='Whether the model is currently deployed')),
                ('deployed_at', models.DateTimeField(blank=True, help_text='When the model was deployed', null=True)),
                ('endpoint_resource_name', models.CharField(blank=True, help_text='Vertex AI Endpoint resource name where model is deployed', max_length=500)),
                ('artifacts', models.JSONField(default=dict, help_text='Paths to generated artifacts (model, embeddings, etc.)')),
                ('training_history_json', models.JSONField(default=dict, help_text='Cached training history data (loss curves, metrics)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
                ('error_stage', models.CharField(blank=True, help_text='Pipeline stage where error occurred', max_length=100)),
                ('error_details', models.JSONField(default=dict, help_text='Detailed error information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When training started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed/failed', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When training is scheduled to start', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total training duration in seconds', null=True)),
                ('base_experiment', models.ForeignKey(blank=True, help_text='Quick test experiment this training run is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to='ml_platform.quicktest')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated the training run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(help_text='Dataset used for training', on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='ml_platform.dataset')),
                ('feature_config', models.ForeignKey(help_text='Feature configuration used for training', on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='ml_platform.featureconfig')),
                ('ml_model', models.ForeignKey(help_text='Parent model/endpoint this training run belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='ml_platform.modelendpoint')),
                ('model_config', models.ForeignKey(help_text='Model configuration (architecture) used for training', on_delete=django.db.models.deletion.PROTECT, related_name='training_runs', to='ml_platform.modelconfig')),
            ],
            options={
                'verbose_name': 'Training Run',
                'verbose_name_plural': 'Training Runs',
                'ordering': ['-created_at'],
                'unique_together': {('ml_model', 'run_number')},
            },
        ),
    ]
