# Generated by Django 4.2.26 on 2026-01-16 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0049_add_ranking_metrics_to_quicktest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this schedule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the schedule')),
                ('schedule_type', models.CharField(choices=[('once', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], help_text='Type of schedule (once, daily, weekly)', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, help_text="Specific datetime for one-time execution (for 'once' type)", null=True)),
                ('schedule_time', models.TimeField(blank=True, help_text="Time of day for recurring execution (HH:MM for 'daily'/'weekly' types)", null=True)),
                ('schedule_day_of_week', models.IntegerField(blank=True, help_text='Day of week for weekly schedules (0=Monday, 6=Sunday)', null=True)),
                ('schedule_timezone', models.CharField(default='UTC', help_text='Timezone for schedule execution', max_length=50)),
                ('training_params', models.JSONField(default=dict, help_text='Training hyperparameters (epochs, batch_size, learning_rate, etc.)')),
                ('gpu_config', models.JSONField(default=dict, help_text='GPU configuration (machine_type, accelerator_type, accelerator_count)')),
                ('evaluator_config', models.JSONField(default=dict, help_text='Model evaluation configuration (blessing thresholds, metrics)')),
                ('deployment_config', models.JSONField(default=dict, help_text='Deployment configuration (auto_deploy, endpoint settings)')),
                ('cloud_scheduler_job_name', models.CharField(blank=True, help_text='Full Cloud Scheduler job resource name', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current status of the schedule', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='When the schedule last triggered a training run', null=True)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='When the schedule will next trigger (calculated)', null=True)),
                ('total_runs', models.IntegerField(default=0, help_text='Total number of training runs triggered by this schedule')),
                ('successful_runs', models.IntegerField(default=0, help_text='Number of successful (completed/blessed) training runs')),
                ('failed_runs', models.IntegerField(default=0, help_text='Number of failed/cancelled training runs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_experiment', models.ForeignKey(blank=True, help_text='Base experiment this schedule was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_schedules', to='ml_platform.quicktest')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_training_schedules', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(help_text='Dataset to use for scheduled training', on_delete=django.db.models.deletion.PROTECT, related_name='training_schedules', to='ml_platform.dataset')),
                ('feature_config', models.ForeignKey(help_text='Feature configuration to use for scheduled training', on_delete=django.db.models.deletion.PROTECT, related_name='training_schedules', to='ml_platform.featureconfig')),
                ('ml_model', models.ForeignKey(help_text='Parent model/endpoint this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='training_schedules', to='ml_platform.modelendpoint')),
                ('model_config', models.ForeignKey(help_text='Model configuration (architecture) to use for scheduled training', on_delete=django.db.models.deletion.PROTECT, related_name='training_schedules', to='ml_platform.modelconfig')),
            ],
            options={
                'verbose_name': 'Training Schedule',
                'verbose_name_plural': 'Training Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Schedule that triggered this run (null for manual runs)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to='training.trainingschedule'),
        ),
    ]
