# Generated by Django 4.2.26 on 2026-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_add_training_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='registered_at',
            field=models.DateTimeField(blank=True, help_text='When the model was registered to Model Registry', null=True),
        ),
    ]
