# Generated by Django 4.2.26 on 2026-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_registered_at_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='schedule_config',
            field=models.JSONField(default=dict, help_text='Embedded schedule configuration (schedule_type, schedule_time, etc.)'),
        ),
    ]
