# Generated by Django 4.2.26 on 2026-01-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_trainingrun_vertex_parent_model_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingschedule',
            name='schedule_day_of_month',
            field=models.IntegerField(blank=True, help_text='Day of month for monthly schedules (1-28)', null=True),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='schedule_type',
            field=models.CharField(choices=[('once', 'One-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Type of schedule (once, daily, weekly)', max_length=20),
        ),
    ]
