# Generated by Django 4.2.26 on 2026-01-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0049_add_ranking_metrics_to_quicktest'),
        ('training', '0007_add_registered_model'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registeredmodel',
            name='unique_ml_model_model_name',
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='vertex_pipeline_job_id',
            field=models.CharField(blank=True, help_text='Short pipeline job ID for display', max_length=255),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name='vertex_pipeline_job_name',
            field=models.CharField(blank=True, help_text='Full Vertex AI pipeline job resource name', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingschedule',
            name='schedule_day_of_month',
            field=models.IntegerField(blank=True, help_text='Day of month for monthly schedules (1-31)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registeredmodel',
            unique_together={('ml_model', 'model_name')},
        ),
    ]
