# Generated by Django 4.2.26 on 2026-01-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_deployment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployedEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Cloud Run service name (unique across project)', max_length=63, unique=True)),
                ('service_url', models.URLField(blank=True, help_text='Cloud Run service URL')),
                ('deployed_version', models.CharField(blank=True, help_text='Currently deployed model version', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether endpoint exists and is active')),
                ('deployment_config', models.JSONField(default=dict, help_text='Last deployment configuration (instances, memory, cpu, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deployed_training_run', models.ForeignKey(blank=True, help_text='Training run currently deployed to this endpoint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='training.trainingrun')),
                ('registered_model', models.ForeignKey(help_text='Model this endpoint belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deployed_endpoints', to='training.registeredmodel')),
            ],
            options={
                'verbose_name': 'Deployed Endpoint',
                'verbose_name_plural': 'Deployed Endpoints',
                'ordering': ['-updated_at'],
            },
        ),
    ]
