# Generated by Django 4.2.26 on 2026-01-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_add_deployed_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='deploy_enabled',
            field=models.BooleanField(default=False, help_text='Whether auto-deployment to Cloud Run is enabled'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='deployed_endpoint',
            field=models.ForeignKey(blank=True, help_text='Cloud Run endpoint this model is deployed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_training_runs', to='training.deployedendpoint'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='deployment_completed_at',
            field=models.DateTimeField(blank=True, help_text='When deployment completed', null=True),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='deployment_error',
            field=models.TextField(blank=True, default='', help_text='Error message if deployment failed'),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='deployment_started_at',
            field=models.DateTimeField(blank=True, help_text='When deployment started', null=True),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='deployment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Status of the deployment process', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('submitting', 'Submitting'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('not_blessed', 'Not Blessed'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('deploy_failed', 'Deploy Failed')], db_index=True, default='pending', help_text='Current status of the training run', max_length=20),
        ),
    ]
