# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_add_deployment_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedendpoint',
            name='model_deleted',
            field=models.BooleanField(
                default=False,
                help_text='Whether the underlying model has been deleted from Vertex AI',
            ),
        ),
    ]
