# Generated by Django 4.2.26 on 2026-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_add_model_deleted_to_deployed_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='auc_roc',
            field=models.FloatField(blank=True, help_text='AUC-ROC (validation set)', null=True),
        ),
        migrations.AddField(
            model_name='trainingrun',
            name='test_auc_roc',
            field=models.FloatField(blank=True, help_text='AUC-ROC (test set)', null=True),
        ),
    ]
