"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-oxm+z$13hoban3g2+4+9g!45o(2di=68a89p6thi*=lqy!2q57')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Project apps
    'ml_platform',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Added for static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration - supports both SQLite (local) and PostgreSQL (Cloud SQL)
DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite')

if DB_ENGINE == 'postgresql':
    db_host = os.environ.get('DB_HOST', '127.0.0.1')
    # When using Cloud SQL Unix socket in Cloud Run, PORT must be empty
    # Only use port 5433 for local development with Cloud SQL Proxy (TCP)
    db_port = '' if db_host.startswith('/cloudsql/') else os.environ.get('DB_PORT', '5433')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'b2b_recs_dev'),
            'USER': os.environ.get('DB_USER', 'django_user'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': db_host,
            'PORT': db_port,
        }
    }
else:
    # SQLite (fallback for local development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'system_dashboard'
LOGOUT_REDIRECT_URL = 'login'

# GCP Configuration
GCP_PROJECT_ID = os.environ.get('GCP_PROJECT_ID', 'b2b-recs')
GCP_LOCATION = os.environ.get('GCP_LOCATION', 'europe-central2')  # Warsaw, Poland

# =============================================================================
# VERTEX AI PIPELINES CONFIGURATION
# =============================================================================

VERTEX_AI_PROJECT = os.environ.get('GCP_PROJECT_ID', 'b2b-recs')
VERTEX_AI_LOCATION = os.environ.get('VERTEX_AI_LOCATION', 'europe-central2')

# GCS Buckets for ML Pipelines
GCS_QUICKTEST_BUCKET = os.environ.get('GCS_QUICKTEST_BUCKET', 'b2b-recs-quicktest-artifacts')
GCS_TRAINING_BUCKET = os.environ.get('GCS_TRAINING_BUCKET', 'b2b-recs-training-artifacts')
GCS_PIPELINE_STAGING_BUCKET = os.environ.get('GCS_PIPELINE_STAGING_BUCKET', 'b2b-recs-pipeline-staging')

# Pipeline compute defaults
QUICKTEST_MACHINE_TYPE = os.environ.get('QUICKTEST_MACHINE_TYPE', 'n1-standard-4')
QUICKTEST_DEFAULT_EPOCHS = int(os.environ.get('QUICKTEST_DEFAULT_EPOCHS', '10'))
QUICKTEST_DEFAULT_BATCH_SIZE = int(os.environ.get('QUICKTEST_DEFAULT_BATCH_SIZE', '4096'))
QUICKTEST_DEFAULT_LEARNING_RATE = float(os.environ.get('QUICKTEST_DEFAULT_LEARNING_RATE', '0.001'))

# Polling interval for pipeline status checks (seconds)
PIPELINE_POLL_INTERVAL = int(os.environ.get('PIPELINE_POLL_INTERVAL', '10'))

# TFX Compiler Image (Pre-built Docker image for pipeline compilation)
# This image is hosted in the central platform project and shared across all client projects.
# It contains TFX, KFP, and all dependencies needed to compile pipelines for Vertex AI.
# Using a pre-built image reduces compilation time from 12-15 min to 1-2 min.
# Note: Currently using b2b-recs project; migrate to b2b-recs-platform for production multi-tenant
TFX_COMPILER_IMAGE = os.environ.get(
    'TFX_COMPILER_IMAGE',
    'europe-central2-docker.pkg.dev/b2b-recs/tfx-builder/tfx-compiler:latest'
)

# =============================================================================
# MLFLOW CONFIGURATION (DEPRECATED - kept for backward compatibility)
# =============================================================================
# MLflow has been replaced with direct GCS storage for training metrics.
# This setting is only used for historical experiments that have mlflow_run_id.
# New experiments use training_metrics.json in GCS instead.

MLFLOW_TRACKING_URI = os.environ.get(
    'MLFLOW_TRACKING_URI',
    'https://mlflow-server-555035914949.europe-central2.run.app'
)

# Logging Configuration
# Ensures exceptions are logged to stdout/stderr for Cloud Run visibility
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',  # Log all request errors
            'propagate': False,
        },
        'ml_platform': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Cloud Run / Production Security Settings
if not DEBUG:
    # Trust the X-Forwarded-Proto header from Cloud Run's load balancer
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Cookie settings for HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Additional security headers
    SECURE_SSL_REDIRECT = False  # Cloud Run handles this
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
