#!/usr/bin/env python3
"""
Test ranking model Reduction.SUM fix via Vertex AI Custom Job.

Generates trainer code via TrainerModuleGenerator (which includes the GPU fix),
uploads to GCS, and submits a Vertex AI Custom Job with 2x T4 GPUs using
Transform artifacts from a previous training run.

Usage:
    # Default: FeatureConfig 42, ModelConfig 36, tr-69 artifacts, 3 epochs, 2x T4
    ./venv/bin/python scripts/test_services_trainer.py

    # Dry run (generate code without submitting job)
    ./venv/bin/python scripts/test_services_trainer.py --dry-run

    # Wait for completion and fetch metrics
    ./venv/bin/python scripts/test_services_trainer.py --wait --timeout 30
"""

import argparse
import logging
import os
import sys
from datetime import datetime

# Setup Django
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)
os.chdir(project_root)
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

import django
django.setup()

from ml_platform.models import FeatureConfig, ModelConfig
from ml_platform.configs.services import TrainerModuleGenerator, validate_python_code

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
logger = logging.getLogger(__name__)

PROJECT_ID = 'b2b-recs'
REGION = 'europe-west4'  # GPU training region (T4 quota approved)
STAGING_BUCKET = 'b2b-recs-pipeline-staging'  # For reading pipeline artifacts
JOB_STAGING_BUCKET = 'b2b-recs-gpu-staging'  # For job staging (must match REGION)
ARTIFACTS_BUCKET = 'b2b-recs-quicktest-artifacts'  # For test output
TRAINER_IMAGE = 'europe-central2-docker.pkg.dev/b2b-recs/tfx-builder/tfx-trainer-gpu:latest'


def find_artifacts(source_run: str) -> dict:
    """Find Transform artifacts from a completed training run."""
    from google.cloud import storage

    client = storage.Client()
    bucket = client.bucket(STAGING_BUCKET)

    prefix = f'pipeline_root/{source_run}/'
    blobs = list(bucket.list_blobs(prefix=prefix))
    paths = [b.name for b in blobs]

    transform_base = None
    schema_path = None

    for p in paths:
        if 'Transform_' in p and '/transform_graph/' in p and not transform_base:
            parts = p.split('/')
            for i, part in enumerate(parts):
                if part.startswith('Transform_'):
                    transform_base = '/'.join(parts[:i+1])
                    break
        if 'SchemaGen_' in p and 'schema.pbtxt' in p:
            schema_path = p

    if not transform_base or not schema_path:
        raise ValueError(f"Could not find artifacts in {prefix}")

    return {
        'transform_graph': f'gs://{STAGING_BUCKET}/{transform_base}/transform_graph',
        'transformed_examples_train': f'gs://{STAGING_BUCKET}/{transform_base}/transformed_examples/Split-train',
        'transformed_examples_eval': f'gs://{STAGING_BUCKET}/{transform_base}/transformed_examples/Split-eval',
        'schema': f'gs://{STAGING_BUCKET}/{schema_path}',
    }


def create_runner_script(artifacts: dict, trainer_gcs_path: str, output_path: str,
                         gcs_output_path: str, epochs: int, batch_size: int,
                         learning_rate: float, gpu_count: int) -> str:
    """Create the script that will run inside the CustomJob."""

    return f'''#!/usr/bin/env python3
"""Trainer runner script for CustomJob - testing ranking model GPU fix."""
import os
import sys
import logging
import tempfile
import subprocess

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
logger = logging.getLogger(__name__)

def main():
    logger.info("="*60)
    logger.info("RANKING MODEL GPU FIX TEST (Reduction.SUM + batch scaling)")
    logger.info("="*60)

    work_dir = tempfile.mkdtemp(prefix='trainer_test_')
    logger.info(f"Work dir: {{work_dir}}")

    # Download trainer module (generated by services.py with Reduction.SUM fix)
    trainer_local = os.path.join(work_dir, 'trainer_module.py')
    logger.info(f"Downloading trainer from {trainer_gcs_path}")
    subprocess.run(['gsutil', 'cp', '{trainer_gcs_path}', trainer_local], check=True)

    # Download transform graph
    transform_local = os.path.join(work_dir, 'transform_graph')
    os.makedirs(transform_local, exist_ok=True)
    logger.info(f"Downloading transform graph from {artifacts['transform_graph']}")
    subprocess.run(['gsutil', '-m', 'rsync', '-r', '{artifacts['transform_graph']}', transform_local], check=True)

    # Download schema
    schema_local = os.path.join(work_dir, 'schema.pbtxt')
    logger.info(f"Downloading schema from {artifacts['schema']}")
    subprocess.run(['gsutil', 'cp', '{artifacts['schema']}', schema_local], check=True)

    # Import trainer module
    logger.info("Importing trainer module...")
    sys.path.insert(0, work_dir)
    import importlib.util
    spec = importlib.util.spec_from_file_location("trainer_module", trainer_local)
    trainer = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(trainer)

    # Create FnArgs
    class FnArgs:
        pass

    fn_args = FnArgs()
    fn_args.train_files = ['{artifacts['transformed_examples_train']}/*']
    fn_args.eval_files = ['{artifacts['transformed_examples_eval']}/*']
    fn_args.transform_output = transform_local
    fn_args.schema_file = schema_local
    fn_args.serving_model_dir = os.path.join(work_dir, 'serving_model')
    fn_args.model_run_dir = os.path.join(work_dir, 'model_run')
    fn_args.train_steps = None
    fn_args.eval_steps = None
    fn_args.custom_config = {{
        'epochs': {epochs},
        'batch_size': {batch_size},
        'learning_rate': {learning_rate},
        'gcs_output_path': '{gcs_output_path}',
        'gpu_enabled': True,
        'gpu_count': {gpu_count},
    }}

    # Create data accessor (custom implementation for standalone Custom Job)
    class DataAccessor:
        def tf_dataset_factory(self, file_pattern, options, schema):
            import tensorflow as tf

            if isinstance(file_pattern, list):
                file_pattern = file_pattern[0]

            files = tf.io.gfile.glob(file_pattern)
            logger.info(f"Found {{len(files)}} files matching {{file_pattern}}")

            dataset = tf.data.TFRecordDataset(files, compression_type='GZIP')

            import tensorflow_transform as tft
            tf_transform_output = tft.TFTransformOutput(fn_args.transform_output)
            feature_spec = tf_transform_output.transformed_feature_spec()

            def parse_fn(example):
                parsed = tf.io.parse_single_example(example, feature_spec)
                expanded = {{}}
                for key, value in parsed.items():
                    if len(value.shape) == 0:  # Scalar
                        expanded[key] = tf.expand_dims(value, 0)
                    else:
                        expanded[key] = value
                return expanded

            dataset = dataset.map(parse_fn, num_parallel_calls=tf.data.AUTOTUNE)
            dataset = dataset.batch(options.batch_size)

            # Handle label_key for ranking models - extract label from features
            label_key = getattr(options, 'label_key', None)
            if label_key:
                logger.info(f"Ranking model: extracting label_key='{{label_key}}' from features")
                def extract_label(features):
                    label = features.pop(label_key)
                    return features, label
                dataset = dataset.map(extract_label, num_parallel_calls=tf.data.AUTOTUNE)

            dataset = dataset.prefetch(tf.data.AUTOTUNE)
            return dataset

    fn_args.data_accessor = DataAccessor()

    os.makedirs(fn_args.serving_model_dir, exist_ok=True)
    os.makedirs(fn_args.model_run_dir, exist_ok=True)

    logger.info("="*60)
    logger.info("STARTING TRAINING")
    logger.info(f"  Epochs: {epochs}")
    logger.info(f"  Batch size: {batch_size}")
    logger.info(f"  Learning rate: {learning_rate}")
    logger.info(f"  GPU count: {gpu_count}")
    logger.info("="*60)

    trainer.run_fn(fn_args)

    logger.info("="*60)
    logger.info("TRAINING COMPLETED SUCCESSFULLY")
    logger.info("="*60)

    logger.info(f"Uploading model to {output_path}")
    subprocess.run(['gsutil', '-m', 'cp', '-r', fn_args.serving_model_dir, '{output_path}'], check=True)

if __name__ == '__main__':
    main()
'''


def wait_for_job_completion(job, timeout_minutes: int = 30) -> str:
    """Wait for job to complete and return final state."""
    import time
    from google.cloud import aiplatform

    logger.info(f"Waiting for job completion (timeout: {timeout_minutes} min)...")
    start_time = time.time()
    timeout_seconds = timeout_minutes * 60
    job_name = job.resource_name

    while True:
        current_job = aiplatform.CustomJob.get(job_name)
        state = current_job.state.name
        elapsed = int(time.time() - start_time)

        if state in ['JOB_STATE_SUCCEEDED', 'JOB_STATE_FAILED', 'JOB_STATE_CANCELLED']:
            logger.info(f"Job finished with state: {state} (after {elapsed}s)")
            return state

        if elapsed > timeout_seconds:
            logger.error(f"Job timed out after {timeout_minutes} minutes")
            return 'TIMEOUT'

        logger.info(f"Job state: {state} (elapsed: {elapsed}s)")
        time.sleep(30)


def fetch_metrics_from_gcs(gcs_output_path: str) -> dict:
    """Fetch training_metrics.json from GCS and extract final metrics."""
    from google.cloud import storage
    import json

    path = gcs_output_path.replace('gs://', '')
    bucket_name = path.split('/')[0]
    blob_path = '/'.join(path.split('/')[1:]) + '/training_metrics.json'

    logger.info(f"Fetching metrics from gs://{bucket_name}/{blob_path}")

    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)

    if not blob.exists():
        logger.warning(f"Metrics file not found: {blob_path}")
        return {}

    content = blob.download_as_string()
    metrics_data = json.loads(content)

    final_metrics = metrics_data.get('final_metrics', {})
    logger.info(f"Retrieved final metrics: {final_metrics}")

    return final_metrics


def main():
    parser = argparse.ArgumentParser(
        description='Test ranking model Reduction.SUM fix via Vertex AI Custom Job'
    )
    parser.add_argument('--feature-config-id', type=int, default=42,
                        help='FeatureConfig ID (default: 42)')
    parser.add_argument('--model-config-id', type=int, default=36,
                        help='ModelConfig ID (default: 36)')
    parser.add_argument('--source-training-run', default='tr-69-20260302-185051',
                        help='Source training run for artifacts (default: tr-69-20260302-185051)')
    parser.add_argument('--epochs', type=int, default=3,
                        help='Training epochs (default: 3)')
    parser.add_argument('--batch-size', type=int, default=8192,
                        help='Batch size (default: 8192)')
    parser.add_argument('--learning-rate', type=float, default=0.002,
                        help='Learning rate (default: 0.002)')
    parser.add_argument('--gpu-count', type=int, default=2,
                        help='Number of GPUs (default: 2)')
    parser.add_argument('--dry-run', action='store_true',
                        help='Generate code but do not submit job')
    parser.add_argument('--wait', action='store_true',
                        help='Wait for job completion and fetch metrics')
    parser.add_argument('--timeout', type=int, default=30,
                        help='Timeout in minutes for --wait (default: 30)')

    args = parser.parse_args()

    from google.cloud import storage, aiplatform

    run_id = f'ranking-fix-{datetime.now().strftime("%Y%m%d-%H%M%S")}'
    gcs_output_path = f'gs://{ARTIFACTS_BUCKET}/{run_id}'
    logger.info(f"Run ID: {run_id}")

    # 1. Load configs from database
    logger.info(f"Loading FeatureConfig {args.feature_config_id} and ModelConfig {args.model_config_id}...")

    feature_config = FeatureConfig.objects.get(id=args.feature_config_id)
    model_config = ModelConfig.objects.get(id=args.model_config_id)

    logger.info(f"  FeatureConfig: {feature_config.name} (ID: {feature_config.id})")
    logger.info(f"  ModelConfig: {model_config.name} (ID: {model_config.id})")
    logger.info(f"  Model type: {model_config.model_type}")
    logger.info(f"  Loss function: {model_config.loss_function}")

    # 2. Generate trainer code using TrainerModuleGenerator (includes the fix)
    logger.info("Generating trainer_module.py using TrainerModuleGenerator...")
    generator = TrainerModuleGenerator(feature_config, model_config)
    trainer_code = generator.generate()

    # Validate the generated code
    is_valid, error_msg, error_line = validate_python_code(trainer_code, 'trainer')
    if not is_valid:
        logger.error(f"Generated code is INVALID: {error_msg} at line {error_line}")
        with open('/tmp/invalid_trainer.py', 'w') as f:
            f.write(trainer_code)
        logger.error("Saved invalid code to /tmp/invalid_trainer.py")
        sys.exit(1)

    logger.info("Generated code is syntactically valid")

    # Verify fix is present in generated code
    fix_checks = {
        'Reduction.SUM': 'Reduction.SUM' in trainer_code,
        'batch-size division': 'tf.shape(labels)[0]' in trainer_code,
    }
    for check_name, passed in fix_checks.items():
        if passed:
            logger.info(f"  VERIFIED: {check_name} is present in generated code")
        else:
            logger.error(f"  WARNING: {check_name} NOT found in generated code!")

    # Override epochs with test value
    import re
    trainer_code = re.sub(r'EPOCHS = \d+', f'EPOCHS = {args.epochs}', trainer_code)
    trainer_code = re.sub(r'LEARNING_RATE = [\d.]+', f'LEARNING_RATE = {args.learning_rate}', trainer_code)

    # 3. Find artifacts from source training run
    logger.info(f"Finding artifacts from {args.source_training_run}...")
    artifacts = find_artifacts(args.source_training_run)
    for k, v in artifacts.items():
        logger.info(f"  {k}: {v}")

    # 4. Upload trainer code to GCS
    client = storage.Client()
    bucket = client.bucket(ARTIFACTS_BUCKET)
    trainer_blob_path = f'{run_id}/trainer_module.py'
    bucket.blob(trainer_blob_path).upload_from_string(trainer_code)
    trainer_gcs_path = f'gs://{ARTIFACTS_BUCKET}/{trainer_blob_path}'
    logger.info(f"Uploaded trainer to {trainer_gcs_path}")

    # 5. Create and upload runner script
    output_path = f'{gcs_output_path}/model'
    runner_script = create_runner_script(
        artifacts, trainer_gcs_path, output_path, gcs_output_path,
        args.epochs, args.batch_size, args.learning_rate, args.gpu_count
    )
    runner_blob_path = f'{run_id}/runner.py'
    bucket.blob(runner_blob_path).upload_from_string(runner_script)
    runner_gcs_path = f'gs://{ARTIFACTS_BUCKET}/{runner_blob_path}'
    logger.info(f"Uploaded runner to {runner_gcs_path}")

    if args.dry_run:
        logger.info("DRY RUN - not submitting")
        logger.info(f"Generated trainer saved to: {trainer_gcs_path}")
        logger.info(f"You can inspect it with: gsutil cat {trainer_gcs_path}")
        return

    # 6. Submit CustomJob
    aiplatform.init(project=PROJECT_ID, location=REGION)

    machine_type = 'n1-standard-16' if args.gpu_count >= 2 else 'n1-standard-8'

    job = aiplatform.CustomJob(
        display_name=f'ranking-fix-test-{run_id}',
        worker_pool_specs=[{
            'machine_spec': {
                'machine_type': machine_type,
                'accelerator_type': 'NVIDIA_TESLA_T4',
                'accelerator_count': args.gpu_count,
            },
            'replica_count': 1,
            'container_spec': {
                'image_uri': TRAINER_IMAGE,
                'command': ['bash', '-c',
                            f'gsutil cp {runner_gcs_path} /tmp/runner.py && python /tmp/runner.py'],
            },
        }],
        staging_bucket=f'gs://{JOB_STAGING_BUCKET}',
    )

    logger.info("Submitting CustomJob...")
    job.submit()

    logger.info(f"""
================================================================================
CUSTOM JOB SUBMITTED - Ranking Model GPU Fix Test (Reduction.SUM)
================================================================================
Run ID: {run_id}
Job: {job.resource_name}

Config:
  FeatureConfig: {feature_config.name} (ID: {feature_config.id})
  ModelConfig: {model_config.name} (ID: {model_config.id})
  Epochs: {args.epochs}
  Batch size: {args.batch_size}
  Learning rate: {args.learning_rate}
  GPU: {args.gpu_count}x T4

Monitor:
  gcloud ai custom-jobs describe {job.resource_name.split('/')[-1]} --region={REGION}

Logs:
  gcloud logging read 'resource.type="ml_job" AND resource.labels.job_id="{job.resource_name.split('/')[-1]}"' \\
      --project={PROJECT_ID} --limit=100 --format='value(textPayload)'

Generated trainer:
  gsutil cat {trainer_gcs_path}

Output:
  Model: {output_path}
  Metrics: {gcs_output_path}/training_metrics.json

Verify metrics after completion:
  gsutil cat {gcs_output_path}/training_metrics.json | python -m json.tool | head -50
================================================================================
""")

    # Wait for completion if requested
    if args.wait:
        job_state = wait_for_job_completion(job, timeout_minutes=args.timeout)

        if job_state == 'JOB_STATE_SUCCEEDED':
            metrics = fetch_metrics_from_gcs(gcs_output_path)
            logger.info(f"""
================================================================================
JOB COMPLETED SUCCESSFULLY - Ranking Model GPU Fix Verified!
================================================================================
Final Metrics:
  RMSE:       {metrics.get('rmse', metrics.get('val_rmse', 'N/A'))}
  MAE:        {metrics.get('mae', metrics.get('val_mae', 'N/A'))}
  Test RMSE:  {metrics.get('test_rmse', 'N/A')}
  Test MAE:   {metrics.get('test_mae', 'N/A')}
  AUC-ROC:    {metrics.get('auc_roc', metrics.get('val_auc_roc', 'N/A'))}
  Loss:       {metrics.get('final_loss', metrics.get('loss', 'N/A'))}

The ranking model trained successfully on {args.gpu_count}x T4 GPU with
MirroredStrategy. The Reduction.SUM + batch-size scaling fix works.
================================================================================
""")
        else:
            logger.error(f"Job failed with state: {job_state}")
            logger.error(f"Check logs for details:")
            logger.error(f"  gcloud logging read 'resource.type=\"ml_job\" AND resource.labels.job_id=\"{job.resource_name.split('/')[-1]}\"' "
                        f"--project={PROJECT_ID} --limit=50 --format='value(textPayload)'")


if __name__ == '__main__':
    main()
