# Generated by Django 5.2.8 on 2025-11-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etlconfiguration',
            name='source_credentials_secret',
        ),
        migrations.RemoveField(
            model_name='etlconfiguration',
            name='source_database',
        ),
        migrations.RemoveField(
            model_name='etlconfiguration',
            name='source_host',
        ),
        migrations.RemoveField(
            model_name='etlconfiguration',
            name='source_port',
        ),
        migrations.RemoveField(
            model_name='etlconfiguration',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='etlrun',
            name='cloud_run_job_id',
        ),
        migrations.RemoveField(
            model_name='etlrun',
            name='rows_extracted',
        ),
        migrations.RemoveField(
            model_name='etlrun',
            name='vertex_job_id',
        ),
        migrations.AddField(
            model_name='etlconfiguration',
            name='cloud_run_service_url',
            field=models.URLField(blank=True, help_text='Cloud Run ETL service URL'),
        ),
        migrations.AddField(
            model_name='etlconfiguration',
            name='cloud_scheduler_job_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='etlconfiguration',
            name='schedule_cron',
            field=models.CharField(blank=True, help_text='Cloud Scheduler cron expression', max_length=100),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='cloud_run_execution_id',
            field=models.CharField(blank=True, help_text='Cloud Run Job execution ID', max_length=255),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='results_detail',
            field=models.JSONField(default=dict, help_text='Detailed results per source and table'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='successful_sources',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='successful_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='total_rows_extracted',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='total_sources',
            field=models.IntegerField(default=0, help_text='Total data sources processed'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='total_tables',
            field=models.IntegerField(default=0, help_text='Total tables processed'),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name (e.g., 'Main Transaction DB')", max_length=255)),
                ('source_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlserver', 'SQL Server'), ('bigquery', 'BigQuery'), ('csv', 'CSV Upload'), ('parquet', 'Parquet Files')], max_length=50)),
                ('source_host', models.CharField(blank=True, max_length=255)),
                ('source_port', models.IntegerField(blank=True, null=True)),
                ('source_database', models.CharField(blank=True, max_length=255)),
                ('source_schema', models.CharField(blank=True, help_text='Database schema (optional)', max_length=255)),
                ('credentials_secret_name', models.CharField(blank=True, help_text='Secret Manager secret name', max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='GCS path to uploaded file', max_length=512)),
                ('bigquery_project', models.CharField(blank=True, max_length=255)),
                ('bigquery_dataset', models.CharField(blank=True, max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('connection_tested', models.BooleanField(default=False)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.TextField(blank=True)),
                ('use_incremental', models.BooleanField(default=False, help_text='Use incremental extraction')),
                ('incremental_column', models.CharField(blank=True, help_text='Column for incremental loads (e.g., updated_at)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etl_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='ml_platform.etlconfiguration')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table_name', models.CharField(help_text='Table name in source database', max_length=255)),
                ('source_query', models.TextField(blank=True, help_text='Optional: custom SQL query instead of table name')),
                ('dest_table_name', models.CharField(help_text="Table name in BigQuery (e.g., 'transactions')", max_length=255)),
                ('dest_dataset', models.CharField(default='raw_data', help_text='BigQuery dataset name', max_length=255)),
                ('sync_mode', models.CharField(choices=[('replace', 'Replace All (Full Refresh)'), ('append', 'Append New Records'), ('incremental', 'Incremental (Date-based)')], default='replace', max_length=20)),
                ('incremental_column', models.CharField(blank=True, help_text='Column for incremental sync', max_length=100)),
                ('last_sync_value', models.CharField(blank=True, help_text='Last synced value (for incremental)', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('row_limit', models.IntegerField(blank=True, help_text='Optional: limit rows for testing', null=True)),
                ('last_row_count', models.IntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ml_platform.datasource')),
            ],
            options={
                'verbose_name': 'Data Source Table',
                'verbose_name_plural': 'Data Source Tables',
                'ordering': ['source_table_name'],
                'unique_together': {('data_source', 'source_table_name')},
            },
        ),
    ]
