# Generated by Django 5.2.8 on 2025-11-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0002_remove_etlconfiguration_source_credentials_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='connection_params',
            field=models.JSONField(blank=True, default=dict, help_text='Additional connection parameters'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='connection_string',
            field=models.TextField(blank=True, help_text='Connection string (MongoDB, Redis, etc.)'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='service_account_file_path',
            field=models.CharField(blank=True, help_text='GCS path to service account JSON', max_length=512),
        ),
        migrations.AddField(
            model_name='datasource',
            name='service_account_json',
            field=models.TextField(blank=True, help_text='Service account JSON key (pasted)'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle Database'), ('sqlserver', 'Microsoft SQL Server'), ('db2', 'IBM DB2'), ('redshift', 'Amazon Redshift'), ('synapse', 'Azure Synapse'), ('bigquery', 'Google BigQuery'), ('snowflake', 'Snowflake'), ('mariadb', 'MariaDB'), ('teradata', 'Teradata'), ('csv', 'CSV Files'), ('parquet', 'Parquet Files'), ('json', 'JSON Files'), ('excel', 'Excel (XLS/XLSX)'), ('txt', 'Text Files'), ('avro', 'Avro Files'), ('mongodb', 'MongoDB'), ('firestore', 'Google Firestore'), ('cassandra', 'Apache Cassandra'), ('dynamodb', 'Amazon DynamoDB'), ('redis', 'Redis')], max_length=50),
        ),
    ]
