# Generated by Django 4.2.26 on 2025-11-13 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ml_platform", "0003_datasource_connection_params_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="credentials_secret_name",
            field=models.CharField(
                blank=True,
                help_text="Secret Manager secret name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_database",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_schema",
            field=models.CharField(
                blank=True,
                help_text="Database schema (optional)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name (e.g., 'Production PostgreSQL')",
                        max_length=255,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("oracle", "Oracle Database"),
                            ("sqlserver", "Microsoft SQL Server"),
                            ("db2", "IBM DB2"),
                            ("redshift", "Amazon Redshift"),
                            ("synapse", "Azure Synapse"),
                            ("bigquery", "Google BigQuery"),
                            ("snowflake", "Snowflake"),
                            ("mariadb", "MariaDB"),
                            ("teradata", "Teradata"),
                            ("csv", "CSV Files"),
                            ("parquet", "Parquet Files"),
                            ("json", "JSON Files"),
                            ("excel", "Excel (XLS/XLSX)"),
                            ("txt", "Text Files"),
                            ("avro", "Avro Files"),
                            ("mongodb", "MongoDB"),
                            ("firestore", "Google Firestore"),
                            ("cassandra", "Apache Cassandra"),
                            ("dynamodb", "Amazon DynamoDB"),
                            ("redis", "Redis"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description"),
                ),
                ("source_host", models.CharField(blank=True, max_length=255)),
                ("source_port", models.IntegerField(blank=True, null=True)),
                ("source_database", models.CharField(blank=True, max_length=255)),
                (
                    "source_schema",
                    models.CharField(
                        blank=True,
                        help_text="Database schema (optional)",
                        max_length=255,
                    ),
                ),
                (
                    "credentials_secret_name",
                    models.CharField(
                        blank=True,
                        help_text="Secret Manager secret name",
                        max_length=255,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="GCS path to uploaded file",
                        max_length=512,
                    ),
                ),
                ("bigquery_project", models.CharField(blank=True, max_length=255)),
                ("bigquery_dataset", models.CharField(blank=True, max_length=255)),
                (
                    "service_account_json",
                    models.TextField(
                        blank=True, help_text="Service account JSON key (pasted)"
                    ),
                ),
                (
                    "service_account_file_path",
                    models.CharField(
                        blank=True,
                        help_text="GCS path to service account JSON",
                        max_length=512,
                    ),
                ),
                (
                    "connection_string",
                    models.TextField(
                        blank=True, help_text="Connection string (MongoDB, Redis, etc.)"
                    ),
                ),
                (
                    "connection_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional connection parameters",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("connection_tested", models.BooleanField(default=False)),
                ("last_test_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_test_status",
                    models.CharField(
                        blank=True, help_text="success or failed", max_length=20
                    ),
                ),
                ("last_test_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="ml_platform.modelendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
                "ordering": ["name"],
                "unique_together": {("model_endpoint", "name")},
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                help_text="Reusable connection (new architecture)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="data_sources",
                to="ml_platform.connection",
            ),
        ),
    ]
