# Generated by Django 4.2.26 on 2025-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_platform", "0004_alter_datasource_credentials_secret_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("model_endpoint", "name")},
        ),
        migrations.AddField(
            model_name="connection",
            name="source_username",
            field=models.CharField(
                blank=True,
                help_text="Database username (for deduplication)",
                max_length=255,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={
                ("model_endpoint", "name"),
                (
                    "model_endpoint",
                    "source_type",
                    "source_host",
                    "source_port",
                    "source_database",
                    "source_username",
                ),
            },
        ),
    ]
