# Generated by Django 4.2.26 on 2025-11-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ml_platform", "0005_alter_connection_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datasource",
            unique_together={("etl_config", "name")},
        ),
    ]
