# Generated by Django 4.2.26 on 2025-11-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_platform", "0006_alter_datasource_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="wizard_completed_steps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of completed step numbers [1,2,3]",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="wizard_last_step",
            field=models.IntegerField(
                default=1, help_text="Last wizard step user completed"
            ),
        ),
    ]
