# Generated by Django 4.2.26 on 2025-11-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0007_datasource_wizard_completed_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='bigquery_dataset',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='bigquery_project',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='connection_params',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='connection_string',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='connection_tested',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='credentials_secret_name',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='last_test_at',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='last_test_message',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='service_account_file_path',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='service_account_json',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_database',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_host',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_port',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='source_schema',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='wizard_completed_steps',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='wizard_last_step',
        ),
        migrations.AddField(
            model_name='connection',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Last time this connection was used by an ETL job', null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Database connection used by this ETL job', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_sources', to='ml_platform.connection'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable this ETL job'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(help_text="ETL job name (e.g., 'Daily Transactions Extract')", max_length=255),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='source_type',
            field=models.CharField(blank=True, help_text='Source type (copied from connection)', max_length=50),
        ),
    ]
