# Generated by Django 4.2.26 on 2025-11-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0008_simplify_datasource_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='aws_access_key_id',
            field=models.CharField(blank=True, help_text='AWS Access Key ID', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='aws_region',
            field=models.CharField(blank=True, default='us-east-1', help_text='AWS region', max_length=50),
        ),
        migrations.AddField(
            model_name='connection',
            name='aws_secret_access_key_secret',
            field=models.CharField(blank=True, help_text='Secret Manager path for AWS Secret Access Key', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='azure_account_key_secret',
            field=models.CharField(blank=True, help_text='Secret Manager path for Azure account key', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='azure_sas_token_secret',
            field=models.CharField(blank=True, help_text='Secret Manager path for SAS token (alternative to account key)', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='azure_storage_account',
            field=models.CharField(blank=True, help_text='Azure storage account name', max_length=255),
        ),
        migrations.AddField(
            model_name='connection',
            name='bucket_path',
            field=models.CharField(blank=True, help_text='Bucket/container path (gs://, s3://, https://)', max_length=512),
        ),
        migrations.AlterField(
            model_name='connection',
            name='file_path',
            field=models.CharField(blank=True, help_text='File path within bucket', max_length=512),
        ),
        migrations.AlterField(
            model_name='connection',
            name='source_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle Database'), ('sqlserver', 'Microsoft SQL Server'), ('db2', 'IBM DB2'), ('redshift', 'Amazon Redshift'), ('synapse', 'Azure Synapse'), ('bigquery', 'Google BigQuery'), ('snowflake', 'Snowflake'), ('mariadb', 'MariaDB'), ('teradata', 'Teradata'), ('gcs', 'Google Cloud Storage'), ('s3', 'AWS S3'), ('azure_blob', 'Azure Blob Storage'), ('mongodb', 'MongoDB'), ('firestore', 'Google Firestore'), ('cassandra', 'Apache Cassandra'), ('dynamodb', 'Amazon DynamoDB'), ('redis', 'Redis')], max_length=50),
        ),
    ]
