# Generated by Django 4.2.26 on 2025-11-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0009_connection_aws_access_key_id_connection_aws_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetable',
            name='schema_name',
            field=models.CharField(blank=True, help_text='Schema name (for databases that support schemas)', max_length=255),
        ),
    ]
