# Generated by Django 4.2.26 on 2025-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0010_add_schema_name_to_datasourcetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetable',
            name='historical_start_date',
            field=models.DateField(blank=True, help_text='Start date for historical backfill (optional)', null=True),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='load_type',
            field=models.CharField(choices=[('transactional', 'Transactional (Append-Only)'), ('catalog', 'Catalog (Daily Snapshot)')], default='transactional', help_text='Type of data load strategy', max_length=20),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_cron',
            field=models.CharField(blank=True, help_text='Custom cron expression', max_length=100),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_day_of_month',
            field=models.IntegerField(blank=True, help_text='Day of month for monthly schedules (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_day_of_week',
            field=models.IntegerField(blank=True, help_text='Day of week for weekly schedules (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Time of day for daily/weekly/monthly schedules', null=True),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom (cron)')], default='manual', help_text='Schedule frequency', max_length=20),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='selected_columns',
            field=models.JSONField(blank=True, default=list, help_text='List of column names to sync (empty = all columns)'),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='timestamp_column',
            field=models.CharField(blank=True, help_text='Column used to track incremental changes (e.g., created_at, updated_at)', max_length=100),
        ),
    ]
