# Generated by Django 4.2.26 on 2025-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0011_add_load_strategy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='cloud_scheduler_job_name',
            field=models.CharField(blank=True, help_text='Cloud Scheduler job name (full path)', max_length=500),
        ),
        migrations.AddField(
            model_name='datasource',
            name='historical_start_date',
            field=models.DateField(blank=True, help_text='Start date for historical backfill', null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_sync_value',
            field=models.CharField(blank=True, help_text='Last synced value for incremental loads', max_length=255),
        ),
        migrations.AddField(
            model_name='datasource',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'Manual Only'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', help_text='ETL run schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='bytes_processed',
            field=models.BigIntegerField(default=0, help_text='Total bytes processed'),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Total duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='extraction_completed_at',
            field=models.DateTimeField(blank=True, help_text='When data extraction completed', null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='extraction_started_at',
            field=models.DateTimeField(blank=True, help_text='When data extraction started', null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='loading_completed_at',
            field=models.DateTimeField(blank=True, help_text='When data loading completed', null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='loading_started_at',
            field=models.DateTimeField(blank=True, help_text='When data loading started', null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='rows_loaded',
            field=models.BigIntegerField(default=0, help_text='Total rows loaded to BigQuery'),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='logs_url',
            field=models.URLField(blank=True, help_text='Cloud Run logs URL'),
        ),
    ]
