# Generated by Django 4.2.26 on 2025-11-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0012_datasource_cloud_scheduler_job_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetable',
            name='file_format',
            field=models.CharField(blank=True, choices=[('csv', 'CSV'), ('parquet', 'Parquet'), ('json', 'JSON/JSONL')], help_text='File format for cloud storage sources', max_length=50),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='file_format_options',
            field=models.JSONField(blank=True, default=dict, help_text='Format-specific options (e.g., CSV delimiter, encoding, has_header)'),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='file_path_prefix',
            field=models.CharField(blank=True, help_text="Folder path prefix for file search (e.g., 'data/transactions/')", max_length=500),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='file_pattern',
            field=models.CharField(blank=True, help_text="File pattern using glob syntax (e.g., '*.csv', 'data_*.parquet')", max_length=200),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='is_file_based',
            field=models.BooleanField(default=False, help_text='True if source is cloud storage files (GCS/S3/Azure), False for databases'),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='load_latest_only',
            field=models.BooleanField(default=True, help_text='If True, load only the latest unprocessed file. If False, load all unprocessed files.'),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schema_fingerprint',
            field=models.CharField(blank=True, help_text='MD5 hash of column names + types for schema validation', max_length=64),
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text="Full path to the file in cloud storage (e.g., 'data/transactions/file.csv')", max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(help_text='File size in bytes')),
                ('file_last_modified', models.DateTimeField(help_text='Last modified timestamp from cloud storage')),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When this file was successfully loaded')),
                ('rows_loaded', models.IntegerField(blank=True, help_text='Number of rows loaded from this file', null=True)),
                ('data_source_table', models.ForeignKey(help_text='The ETL job that processed this file', on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to='ml_platform.datasourcetable')),
                ('etl_run', models.ForeignKey(blank=True, help_text='The ETL run that processed this file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_files', to='ml_platform.etlrun')),
            ],
            options={
                'verbose_name': 'Processed File',
                'verbose_name_plural': 'Processed Files',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['data_source_table', 'file_path'], name='ml_platform_data_so_27476e_idx'), models.Index(fields=['processed_at'], name='ml_platform_process_ef3eea_idx')],
                'unique_together': {('data_source_table', 'file_path')},
            },
        ),
    ]
