# Generated by Django 4.2.26 on 2025-11-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0014_datasourcetable_selected_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_minute',
            field=models.IntegerField(blank=True, help_text='Minute for hourly schedules (0-59)', null=True),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='schedule_timezone',
            field=models.CharField(default='UTC', help_text="Timezone for schedule (auto-detected from user's browser)", max_length=50),
        ),
    ]
