# Generated by Django 4.2.26 on 2025-11-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0015_datasourcetable_schedule_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetable',
            name='column_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Mapping of original column names to sanitized BigQuery column names (e.g., {'DiscountApplied(%)': 'discountapplied'})"),
        ),
    ]
