# Generated by Django 4.2.26 on 2025-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0016_add_column_mapping_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcetable',
            name='estimated_row_count',
            field=models.BigIntegerField(blank=True, help_text='Last estimated row count from most recent ETL run (used for planning/display)', null=True),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='processing_mode',
            field=models.CharField(choices=[('auto', 'Auto-detect (based on row count)'), ('standard', 'Standard (Cloud Run, < 1M rows)'), ('dataflow', 'Dataflow (large-scale, >= 1M rows)')], default='auto', help_text='Processing engine selection: auto-detect, standard (pandas), or dataflow (Apache Beam)', max_length=20),
        ),
        migrations.AddField(
            model_name='datasourcetable',
            name='row_count_threshold',
            field=models.IntegerField(default=1000000, help_text="Threshold for switching to Dataflow when processing_mode='auto' (default: 1 million rows)"),
        ),
    ]
