# Generated by Django 4.2.26 on 2025-11-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0017_add_processing_mode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrun',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='The specific data source this run is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ml_platform.datasource'),
        ),
    ]
