# Generated by Django 4.2.26 on 2025-11-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0018_add_data_source_to_etlrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='When this job last ran', null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_run_message',
            field=models.TextField(blank=True, help_text='Error message or summary from last run'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_run_status',
            field=models.CharField(blank=True, help_text='Status of last run (completed, failed, etc.)', max_length=50),
        ),
    ]
