# Generated by Django 4.2.26 on 2025-12-08 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_platform', '0022_remove_dataset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Feature config name (e.g., 'Rich Features v2')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this feature configuration')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', help_text='Feature config status', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Current version number')),
                ('buyer_model_features', models.JSONField(blank=True, default=list, help_text='Features assigned to BuyerModel (Query Tower)')),
                ('product_model_features', models.JSONField(blank=True, default=list, help_text='Features assigned to ProductModel (Candidate Tower)')),
                ('buyer_model_crosses', models.JSONField(blank=True, default=list, help_text='Cross features for BuyerModel')),
                ('product_model_crosses', models.JSONField(blank=True, default=list, help_text='Cross features for ProductModel')),
                ('buyer_tensor_dim', models.PositiveIntegerField(blank=True, help_text='Total tensor dimensions for BuyerModel', null=True)),
                ('product_tensor_dim', models.PositiveIntegerField(blank=True, help_text='Total tensor dimensions for ProductModel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_configs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(help_text='The dataset this feature config is based on', on_delete=django.db.models.deletion.CASCADE, related_name='feature_configs', to='ml_platform.dataset')),
            ],
            options={
                'verbose_name': 'Feature Config',
                'verbose_name_plural': 'Feature Configs',
                'ordering': ['-updated_at'],
                'unique_together': {('dataset', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FeatureConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Version number')),
                ('buyer_model_features', models.JSONField(help_text='Snapshot of buyer model features')),
                ('product_model_features', models.JSONField(help_text='Snapshot of product model features')),
                ('buyer_model_crosses', models.JSONField(help_text='Snapshot of buyer model crosses')),
                ('product_model_crosses', models.JSONField(help_text='Snapshot of product model crosses')),
                ('buyer_tensor_dim', models.PositiveIntegerField(help_text='Buyer tensor dimensions at this version')),
                ('product_tensor_dim', models.PositiveIntegerField(help_text='Product tensor dimensions at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_config_versions', to=settings.AUTH_USER_MODEL)),
                ('feature_config', models.ForeignKey(help_text='The feature config this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ml_platform.featureconfig')),
            ],
            options={
                'verbose_name': 'Feature Config Version',
                'verbose_name_plural': 'Feature Config Versions',
                'ordering': ['-version'],
                'unique_together': {('feature_config', 'version')},
            },
        ),
    ]
