# Generated by Django 4.2.26 on 2025-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0023_feature_config_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='When code was last generated', null=True),
        ),
        migrations.AddField(
            model_name='featureconfig',
            name='generated_trainer_code',
            field=models.TextField(blank=True, help_text='Auto-generated TFX Trainer module code'),
        ),
        migrations.AddField(
            model_name='featureconfig',
            name='generated_transform_code',
            field=models.TextField(blank=True, help_text='Auto-generated TFX Transform preprocessing_fn code'),
        ),
    ]
