# Generated by Django 4.2.26 on 2025-12-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_platform', '0024_add_generated_code_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_sample_percent', models.IntegerField(default=100, help_text='Percentage of dataset to use (100 = full, future: 5/10/25)')),
                ('epochs', models.IntegerField(default=10, help_text='Number of training epochs (1-15)')),
                ('batch_size', models.IntegerField(default=4096, help_text='Training batch size')),
                ('learning_rate', models.FloatField(default=0.001, help_text='Learning rate for optimizer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitting', 'Submitting'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('vertex_pipeline_job_name', models.CharField(blank=True, help_text='Full Vertex AI pipeline job resource name', max_length=500)),
                ('vertex_pipeline_job_id', models.CharField(blank=True, help_text='Short pipeline job ID for display', max_length=255)),
                ('current_stage', models.CharField(choices=[('pending', 'Pending'), ('example_gen', 'ExampleGen'), ('statistics_gen', 'StatisticsGen'), ('schema_gen', 'SchemaGen'), ('transform', 'Transform'), ('trainer', 'Trainer'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current pipeline stage', max_length=50)),
                ('progress_percent', models.IntegerField(default=0, help_text='Overall progress percentage (0-100)')),
                ('stage_details', models.JSONField(default=list, help_text='List of stage statuses: [{name, status, duration_seconds, error}]')),
                ('loss', models.FloatField(blank=True, help_text='Final training loss', null=True)),
                ('recall_at_10', models.FloatField(blank=True, help_text='Recall@10 metric', null=True)),
                ('recall_at_50', models.FloatField(blank=True, help_text='Recall@50 metric', null=True)),
                ('recall_at_100', models.FloatField(blank=True, help_text='Recall@100 metric', null=True)),
                ('vocabulary_stats', models.JSONField(default=dict, help_text='Vocabulary sizes and OOV rates per feature')),
                ('error_message', models.TextField(blank=True, help_text='Error message if pipeline failed')),
                ('error_stage', models.CharField(blank=True, help_text='Stage where error occurred', max_length=50)),
                ('gcs_artifacts_path', models.CharField(blank=True, help_text="GCS path for this run's artifacts", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When pipeline was submitted to Vertex AI', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When pipeline started running', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When pipeline completed/failed', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Total pipeline duration in seconds', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who initiated the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quick_tests', to=settings.AUTH_USER_MODEL)),
                ('feature_config', models.ForeignKey(help_text='Feature Config being tested', on_delete=django.db.models.deletion.CASCADE, related_name='quick_tests', to='ml_platform.featureconfig')),
            ],
            options={
                'verbose_name': 'Quick Test',
                'verbose_name_plural': 'Quick Tests',
                'ordering': ['-created_at'],
            },
        ),
    ]
