# Generated by Django 4.2.26 on 2025-12-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_platform', '0027_remove_feature_config_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Standard Retrieval v1')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of this configuration')),
                ('model_type', models.CharField(choices=[('retrieval', 'Retrieval'), ('ranking', 'Ranking'), ('multitask', 'Multitask')], default='retrieval', help_text='Type of recommendation model', max_length=20)),
                ('buyer_tower_layers', models.JSONField(default=list, help_text='Buyer/Query tower layer configurations')),
                ('product_tower_layers', models.JSONField(default=list, help_text='Product/Candidate tower layer configurations')),
                ('rating_head_layers', models.JSONField(default=list, help_text='Rating prediction layers for ranking/multitask (after embedding concatenation)')),
                ('output_embedding_dim', models.IntegerField(default=32, help_text='Dimension of final tower output embeddings (must match between towers)')),
                ('share_tower_weights', models.BooleanField(default=False, help_text='Use identical weights for both towers (requires identical architecture)')),
                ('optimizer', models.CharField(choices=[('adagrad', 'Adagrad'), ('adam', 'Adam'), ('sgd', 'SGD')], default='adagrad', help_text='Optimizer algorithm', max_length=20)),
                ('learning_rate', models.FloatField(default=0.1, help_text='Learning rate for optimizer')),
                ('batch_size', models.IntegerField(default=4096, help_text='Training batch size')),
                ('epochs', models.IntegerField(default=5, help_text='Number of training epochs')),
                ('retrieval_weight', models.FloatField(default=1.0, help_text='Weight for retrieval loss in multitask model (0.0-1.0)')),
                ('ranking_weight', models.FloatField(default=0.0, help_text='Weight for ranking loss in multitask model (0.0-1.0)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_model_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configurations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
