# Generated by Django 4.2.26 on 2025-12-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0028_add_model_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='retrieval_algorithm',
            field=models.CharField(choices=[('brute_force', 'Brute Force'), ('scann', 'ScaNN')], default='brute_force', help_text='Algorithm for top-K candidate retrieval', max_length=20),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='scann_leaves_to_search',
            field=models.IntegerField(default=10, help_text='Number of partitions to search at query time'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='scann_num_leaves',
            field=models.IntegerField(default=100, help_text='Number of partitions for ScaNN index (recommended: sqrt(catalog_size))'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='top_k',
            field=models.IntegerField(default=100, help_text='Number of top candidates to retrieve'),
        ),
    ]
