# Generated by Django 4.2.26 on 2025-12-12 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0029_add_retrieval_algorithm_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureconfig',
            name='generated_trainer_code',
        ),
        migrations.AddField(
            model_name='quicktest',
            name='model_config',
            field=models.ForeignKey(blank=True, help_text='Model Config being tested (defines neural network architecture)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_tests', to='ml_platform.modelconfig'),
        ),
        migrations.AlterField(
            model_name='featureconfig',
            name='generated_at',
            field=models.DateTimeField(blank=True, help_text='When transform code was last generated', null=True),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='optimizer',
            field=models.CharField(choices=[('adagrad', 'Adagrad'), ('adam', 'Adam'), ('sgd', 'SGD'), ('rmsprop', 'RMSprop'), ('adamw', 'AdamW'), ('ftrl', 'FTRL')], default='adagrad', help_text='Optimizer algorithm', max_length=20),
        ),
        migrations.AlterField(
            model_name='quicktest',
            name='feature_config',
            field=models.ForeignKey(help_text='Feature Config being tested (defines feature transformations)', on_delete=django.db.models.deletion.CASCADE, related_name='quick_tests', to='ml_platform.featureconfig'),
        ),
    ]
