# Generated by Django 4.2.26 on 2025-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0032_add_rating_column_to_quicktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='date_column',
            field=models.CharField(blank=True, help_text='Column name for temporal split (required for time-based strategies)', max_length=255),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='holdout_days',
            field=models.IntegerField(default=1, help_text='Days to exclude from training for holdout (used with time_holdout strategy)'),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='split_strategy',
            field=models.CharField(choices=[('random', 'Random Split (fastest, may have data leakage)'), ('time_holdout', 'Time Holdout (recommended for recommenders)'), ('strict_time', 'Strict Temporal (train < val < test by date)')], default='random', help_text='How to split data into train/eval sets', max_length=20),
        ),
        migrations.AlterField(
            model_name='quicktest',
            name='data_sample_percent',
            field=models.IntegerField(default=100, help_text='Percentage of dataset to use (5, 10, 25, or 100)'),
        ),
    ]
