# Generated by Django 4.2.26 on 2025-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0034_add_experiment_number_to_quicktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='test_days',
            field=models.IntegerField(default=7, help_text='Number of days for test data (strict_time strategy)'),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='train_days',
            field=models.IntegerField(default=60, help_text='Number of days for training data (strict_time strategy)'),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='val_days',
            field=models.IntegerField(default=7, help_text='Number of days for validation data (strict_time strategy)'),
        ),
    ]
