# Generated by Django 4.2.26 on 2025-12-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0036_add_machine_type_to_quicktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='cloud_build_id',
            field=models.CharField(blank=True, help_text='Cloud Build ID for pipeline compilation', max_length=255),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='cloud_build_run_id',
            field=models.CharField(blank=True, help_text='Run ID used for GCS result path', max_length=255),
        ),
    ]
