# Generated by Django 4.2.26 on 2025-12-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0038_add_experiment_name_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='mlflow_experiment_name',
            field=models.CharField(blank=True, help_text='MLflow experiment name', max_length=255),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='mlflow_run_id',
            field=models.CharField(blank=True, help_text='MLflow run ID for this experiment', max_length=255),
        ),
    ]
