# Generated by Django 4.2.26 on 2025-12-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0039_add_mlflow_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrun',
            name='dataflow_job_id',
            field=models.CharField(blank=True, help_text='Dataflow job ID for large-scale ETL runs (used for accurate status tracking)', max_length=255),
        ),
    ]
