# Generated by Django 4.2.26 on 2026-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0041_add_column_aliases_to_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='training_history_json',
            field=models.JSONField(blank=True, help_text='Cached training history data for fast loading (loss curves, metrics, params)', null=True),
        ),
    ]
