# Generated by Django 4.2.26 on 2026-01-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0043_add_hyperparameter_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='buyer_cross_details',
            field=models.JSONField(blank=True, help_text="List of buyer cross features, e.g. [{'name': 'customer_id × date', 'dim': 16}]", null=True),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='buyer_feature_details',
            field=models.JSONField(blank=True, help_text="List of buyer features with dimensions, e.g. [{'name': 'customer_id', 'dim': 32}]", null=True),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='product_cross_details',
            field=models.JSONField(blank=True, help_text='List of product cross features', null=True),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='product_feature_details',
            field=models.JSONField(blank=True, help_text='List of product features with dimensions', null=True),
        ),
    ]
