# Generated by Django 4.2.26 on 2026-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0046_update_dataset_filter_fields_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='recall_at_5',
            field=models.FloatField(blank=True, help_text='Recall@5 metric', null=True),
        ),
    ]
