# Generated by Django 4.2.26 on 2026-01-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0047_add_recall_at_5_to_quicktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureconfig',
            name='config_type',
            field=models.CharField(
                choices=[('retrieval', 'Retrieval'), ('ranking', 'Ranking')],
                default='retrieval',
                help_text='Derived from target_column presence. Retrieval=no target, Ranking=has target',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='featureconfig',
            name='target_column',
            field=models.JSONField(
                blank=True,
                help_text='Target column for ranking models (e.g., rating, sales, quantity)',
                null=True,
            ),
        ),
    ]
