# Generated by Django - add ranking metrics to QuickTest

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0048_add_ranking_support_to_featureconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='rmse',
            field=models.FloatField(
                blank=True,
                null=True,
                help_text='Root Mean Square Error (validation) - for ranking models'
            ),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='mae',
            field=models.FloatField(
                blank=True,
                null=True,
                help_text='Mean Absolute Error (validation) - for ranking models'
            ),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='test_rmse',
            field=models.FloatField(
                blank=True,
                null=True,
                help_text='Root Mean Square Error (test set) - for ranking models'
            ),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='test_mae',
            field=models.FloatField(
                blank=True,
                null=True,
                help_text='Mean Absolute Error (test set) - for ranking models'
            ),
        ),
    ]
