# Generated by Django 4.2.26 on 2026-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0049_add_ranking_metrics_to_quicktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrun',
            name='error_type',
            field=models.CharField(blank=True, choices=[('init', 'Initialization'), ('validation', 'Validation'), ('extraction', 'Extraction'), ('load', 'Load'), ('unknown', 'Unknown')], help_text='Type of error that caused failure (init, validation, extraction, load)', max_length=20),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='init_completed_at',
            field=models.DateTimeField(blank=True, help_text='When initialization/config loading completed', null=True),
        ),
        migrations.AddField(
            model_name='etlrun',
            name='validation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When BigQuery table validation completed', null=True),
        ),
    ]
