# Generated by Django 4.2.26 on 2026-02-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0050_add_etl_run_error_type_and_stage_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrun',
            name='cloud_run_execution_name',
            field=models.CharField(blank=True, help_text="Cloud Run Job execution name (e.g., 'etl-runner-abc123') for log queries", max_length=255),
        ),
    ]
