# Generated by Django 4.2.26 on 2026-02-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0051_add_cloud_run_execution_name_to_etlrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('bq_total_bytes', models.BigIntegerField(default=0, help_text='Total BQ storage in bytes')),
                ('bq_table_details', models.JSONField(default=list, help_text='Per-table breakdown [{name, bytes, rows}]')),
                ('bq_jobs_completed', models.IntegerField(default=0)),
                ('bq_jobs_failed', models.IntegerField(default=0)),
                ('bq_bytes_billed', models.BigIntegerField(default=0, help_text='Total bytes billed by BQ jobs')),
                ('cloud_run_services', models.JSONField(default=list, help_text='[{name, status, is_ml_serving}]')),
                ('cloud_run_active_services', models.IntegerField(default=0)),
                ('db_size_bytes', models.BigIntegerField(default=0, help_text='PostgreSQL database size in bytes')),
                ('db_table_details', models.JSONField(default=list, help_text='[{name, size_bytes, row_count}]')),
                ('gcs_bucket_details', models.JSONField(default=list, help_text='[{name, total_bytes, object_count}]')),
                ('gcs_total_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resource Metrics',
                'verbose_name_plural': 'Resource Metrics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
