# Generated by Django 4.2.26 on 2026-02-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0052_resourcemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemetrics',
            name='gpu_jobs_by_type',
            field=models.JSONField(default=list, help_text='[{gpu_type, count, hours}]'),
        ),
        migrations.AddField(
            model_name='resourcemetrics',
            name='gpu_jobs_completed',
            field=models.IntegerField(default=0, help_text='Training jobs completed on this day'),
        ),
        migrations.AddField(
            model_name='resourcemetrics',
            name='gpu_jobs_failed',
            field=models.IntegerField(default=0, help_text='Training jobs failed on this day'),
        ),
        migrations.AddField(
            model_name='resourcemetrics',
            name='gpu_jobs_running',
            field=models.IntegerField(default=0, help_text='Training jobs running at snapshot time'),
        ),
        migrations.AddField(
            model_name='resourcemetrics',
            name='gpu_training_hours',
            field=models.FloatField(default=0, help_text='Total GPU-hours for training jobs on this day'),
        ),
    ]
