# Generated by Django 4.2.26 on 2026-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0053_resourcemetrics_gpu_jobs_by_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemetrics',
            name='cloud_run_request_details',
            field=models.JSONField(default=list, help_text='[{name, requests, errors}]'),
        ),
        migrations.AddField(
            model_name='resourcemetrics',
            name='cloud_run_total_requests',
            field=models.IntegerField(default=0, help_text='Total ML serving requests on this day'),
        ),
    ]
