# Generated by Django 4.2.26 on 2026-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0054_resourcemetrics_cloud_run_request_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemetrics',
            name='etl_jobs_completed',
            field=models.IntegerField(default=0, help_text='ETL jobs completed on this day'),
        ),
        migrations.AddField(
            model_name='resourcemetrics',
            name='etl_jobs_failed',
            field=models.IntegerField(default=0, help_text='ETL jobs failed on this day'),
        ),
    ]
