# Generated by Django 4.2.26 on 2026-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0056_modelconfig_model_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemetrics',
            name='collection_errors',
            field=models.JSONField(blank=True, default=list, help_text='Errors from sub-collectors [{collector, error}]'),
        ),
    ]
