# Generated by Django 4.2.26 on 2026-02-07 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0057_add_collection_errors_to_resourcemetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_requests', models.IntegerField(default=0, help_text='Total serving requests on this day')),
                ('error_count', models.IntegerField(default=0, help_text='Total non-2xx responses')),
                ('latency_p50_ms', models.FloatField(default=0, help_text='P50 latency in ms')),
                ('latency_p95_ms', models.FloatField(default=0, help_text='P95 latency in ms')),
                ('latency_p99_ms', models.FloatField(default=0, help_text='P99 latency in ms')),
                ('endpoint_details', models.JSONField(default=list, help_text='[{name, requests, errors, latency_p50_ms, latency_p95_ms, latency_p99_ms}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_endpoint', models.ForeignKey(help_text='The project this metrics row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_metrics', to='ml_platform.modelendpoint')),
            ],
            options={
                'verbose_name': 'Project Metrics',
                'verbose_name_plural': 'Project Metrics',
                'ordering': ['-date'],
                'unique_together': {('date', 'model_endpoint')},
            },
        ),
    ]
