# Generated by Django 4.2.26 on 2026-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0058_projectmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_fee', models.DecimalField(decimal_places=2, default=1900.0, help_text='Monthly license fee in USD', max_digits=10)),
                ('license_discount_pct', models.IntegerField(default=100, help_text='Discount on license fee (0-100, currently 100%)')),
                ('default_margin_pct', models.IntegerField(default=100, help_text='Margin applied to most GCP services (100%)')),
                ('gpu_margin_pct', models.IntegerField(default=50, help_text='Margin applied to Vertex AI / GPU costs (50%)')),
                ('billing_export_project', models.CharField(default='b2b-recs', help_text='GCP project hosting the billing export dataset', max_length=255)),
                ('billing_export_dataset', models.CharField(default='billing_export', help_text='BigQuery dataset name for billing export', max_length=255)),
                ('client_project_id', models.CharField(default='b2b-recs', help_text="This client's GCP project ID (for filtering billing export)", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Config',
                'verbose_name_plural': 'Billing Config',
            },
        ),
        migrations.CreateModel(
            name='BillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Cost date (from billing export usage_start_time)')),
                ('service_name', models.CharField(help_text="GCP service (e.g., 'BigQuery', 'Vertex AI', 'Cloud Run')", max_length=255)),
                ('gcp_cost', models.DecimalField(decimal_places=2, default=0, help_text='Actual GCP charge for this service on this date (USD)', max_digits=10)),
                ('margin_pct', models.IntegerField(default=100, help_text='Margin percentage applied (frozen at snapshot time)')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='gcp_cost * margin_pct / 100', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='gcp_cost + platform_fee', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Billing Snapshot',
                'verbose_name_plural': 'Billing Snapshots',
                'ordering': ['-date'],
                'unique_together': {('date', 'service_name')},
            },
        ),
    ]
