# Generated by Django 4.2.26 on 2026-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0063_quicktest_gpu_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='display_currency',
            field=models.CharField(default='EUR', help_text='Currency code for UI display (e.g., EUR, USD)', max_length=3),
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='usd_to_display_rate',
            field=models.DecimalField(decimal_places=4, default=0.92, help_text='Exchange rate: 1 USD = X display currency (e.g., 0.92 for EUR)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='gpu_margin_pct',
            field=models.IntegerField(default=100, help_text='Margin applied to Vertex AI / GPU costs (100%)'),
        ),
        migrations.AlterField(
            model_name='billingsnapshot',
            name='service_name',
            field=models.CharField(help_text="GCP service (e.g., 'BigQuery', 'Vertex AI — GPU', 'Cloud Run')", max_length=255),
        ),
    ]
