# Generated by Django 4.2.26 on 2026-02-24 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0064_billing_display_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='billingconfig',
            name='license_fee',
            field=models.DecimalField(decimal_places=2, default=1900.0, help_text='Monthly license fee in display currency (EUR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='connection',
            name='model_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='ml_platform.modelendpoint'),
        ),
        migrations.AlterField(
            model_name='etlconfiguration',
            name='model_endpoint',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etl_config', to='ml_platform.modelendpoint'),
        ),
        migrations.AlterField(
            model_name='etlrun',
            name='model_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etl_runs', to='ml_platform.modelendpoint'),
        ),
    ]
