# Generated by Django 4.2.26 on 2026-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0065_etl_models_nullable_model_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicktest',
            name='auc_roc',
            field=models.FloatField(blank=True, help_text='AUC-ROC (validation) - for ranking models with binary labels', null=True),
        ),
        migrations.AddField(
            model_name='quicktest',
            name='test_auc_roc',
            field=models.FloatField(blank=True, help_text='AUC-ROC (test set) - for ranking models with binary labels', null=True),
        ),
    ]
