# Generated by Django 4.2.26 on 2026-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_platform', '0066_quicktest_auc_roc_quicktest_test_auc_roc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmetrics',
            name='cpu_utilization_avg',
            field=models.FloatField(default=0, help_text='Average CPU utilization percentage'),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='instance_count_avg',
            field=models.FloatField(default=0, help_text='Average container instances across all endpoints'),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='instance_count_peak',
            field=models.IntegerField(default=0, help_text='Peak container instances across all endpoints'),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='instance_details',
            field=models.JSONField(default=list, help_text='[{name, peak, avg}]'),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='memory_utilization_avg',
            field=models.FloatField(default=0, help_text='Average memory utilization percentage'),
        ),
        migrations.AddField(
            model_name='projectmetrics',
            name='startup_latency_details',
            field=models.JSONField(default=list, help_text='[{name, p50_ms, p95_ms}]'),
        ),
    ]
